name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Deploy to Hostinger using FTP
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}       # FTP server address (Hostinger's FTP address)
        username: ${{ secrets.FTP_USERNAME }}   # FTP username
        password: ${{ secrets.FTP_PASSWORD }}   # FTP password
        protocol: ftp                           # Use FTP protocol
        local-dir: ./                           # Local directory to deploy
        server-dir: /public_html/testchurch/           # Remote server directory for deployment
        log-level: standard                     # Log level (optional, useful for debugging)
